### PR TITLE
Deprecate DualReferenceCounted

### LINKED ISSUE #445: DualReferenceCounted introduces risk of deadlock
`DualReferenceCounted` wraps an instance of `VanillaReferenceCounted` and one of `TracingReferenceCounted`, delegating all calls that change state (e.g. `reserve`/`release`/`releaseLast`) to both of them. These calls are made in synchronized blocks so as to ensure both child `ReferenceCounted` objects are called in sequence atomically.

This presents a number of issues, 
- If one of the calls fails, the two `ReferenceCounted`s can get out of sync (this currently happens if you called `releaseLast`, with a reference that isn't the last)
- The `onRelease` handler in the children are called in the synchronized block, [introducing the possibility of a deadlock](https://github.com/OpenHFT/Chronicle-Core/blob/e243bfa5095657d6e3ecc877a6302bec41f2c13e/src/main/java/net/openhft/chronicle/core/io/TracingReferenceCounted.java#L121)

[The addition of the ReferenceChangeHandler](https://github.com/OpenHFT/Chronicle-Core/pull/443) adds to this risk. I propose we deprecate `DualReferenceHandler` and use either `TracingReferenceHandler` or `VanillaReferenceHandler` individually depending on if tracing is turned on.

### PR DESCRIPTION
**Pull request by nicktindall**
Fixes #445

I assume the reason for DualReferenceCounted was as a kind of integration test to confirm that the behaviour of Tracing and Vanilla `ReferenceCounted`s was consistent (it wasn't, see changes to `TracingReferenceCounted#releaseLast`).

I think a better way to ensure their consistency is to implement contract tests for the interfaces and run all the implementations through them.

I also found some inconsistencies between the contract and the implementations.

### CODE REVIEW

File: src/main/java/net/openhft/chronicle/core/io/AbstractCloseable.java [hunk 1]
```diff
@@ -43,7 +43,9 @@ public abstract class AbstractCloseable implements ReferenceOwner, ManagedClosea
     @Deprecated(/* remove in x.25 */)
     protected static final boolean DISABLE_THREAD_SAFETY = DISABLE_SINGLE_THREADED_CHECK;
     protected static final boolean DISABLE_DISCARD_WARNING = Jvm.getBoolean("disable.discard.warning", false);
-    protected static final boolean STRICT_DISCARD_WARNING = Jvm.getBoolean("strict.discard.warning", false);
+    @SuppressWarnings("DeprecatedIsStillUsed")
+    @Deprecated(/* remove in x.25 */)
+    protected static final boolean STRICT_DISCARD_WARNING;
```
Comment (nicktindall) [inline src/main/java/net/openhft/chronicle/core/io/AbstractCloseable.java:48]: I don't understand the purpose of this, when true it seemed to use `Jvm.warn` instead of `Slf4jExceptionHandler.WARN` to log the warning that something was discarded without being closed. Using the latter made it hard to test that we warned when that happened, so I just removed this. Happy to un-remove if there's a good reason for its existence.

File: src/main/java/net/openhft/chronicle/core/io/ReferenceCountedTracer.java [hunk 2]
```diff
@@ -28,10 +28,7 @@ public interface ReferenceCountedTracer extends ReferenceCounted {
     @NotNull
     static ReferenceCountedTracer onReleased(final Runnable onRelease, Supplier<String> uniqueId, Class<?> type) {
         return Jvm.isResourceTracing()
-                ? new DualReferenceCounted(
-                new TracingReferenceCounted(onRelease, uniqueId.get(), type),
-                new VanillaReferenceCounted(() -> {
-                }, type))
+                ? new TracingReferenceCounted(onRelease, uniqueId.get(), type)
```
Comment (nicktindall) [inline src/main/java/net/openhft/chronicle/core/io/ReferenceCountedTracer.java:31]: Just use `TracingReferenceCounted` instead of dual

File: src/main/java/net/openhft/chronicle/core/io/TracingReferenceCounted.java [hunk 3]
```diff
@@ -142,18 +140,10 @@ public void releaseLast(ReferenceOwner id) throws IllegalStateException {
         if (references.size() <= 1) {
             release(id);
         } else {
-            Exception e0 = null;
-            try {
-                release(id);
-            } catch (Exception e) {
-                e0 = e;
-            }
```
Comment (nicktindall) [inline src/main/java/net/openhft/chronicle/core/io/TracingReferenceCounted.java:150]: This behaviour I think is incorrect, it would perform the release regardless of whether the reference was the last, then throw the exception if it wasn't the last, this differed from the behaviour in `VanillaReferenceCounted` where the count was only decremented if it was <= 1 (which feels more correct)

Happy to change Vanilla to match this behaviour instead if we think it is correct.

Whatever happens they should probably be consistent. This was where I noticed the problem with Dual.

File: src/main/java/net/openhft/chronicle/core/io/TracingReferenceCounted.java [hunk 4]
```diff
@@ -230,11 +220,18 @@ public void throwExceptionIfReleased() throws ClosedIllegalStateException {
...
+            if (refCount() > 0) {
+                if (!unmonitored && !AbstractCloseable.DISABLE_DISCARD_WARNING) {
+                    Jvm.warn().on(type, "Discarded without being released by " + referencesAsString(), createdHere);
+                }
+                references.clear();
+                runOnRelease = true;
             }
+        }
+        // Run outside the synchronized block to avoid risk of deadlock
+        if (runOnRelease) {
```
Comment (nicktindall) [inline src/main/java/net/openhft/chronicle/core/io/TracingReferenceCounted.java:243]: I changed warnAndRelease to actually clear the references, so any subsequent calls to reserve or release would fail. I did this with Tracing and Vanilla

File: src/test/java/net/openhft/chronicle/core/io/TracingReferenceCountedTest.java [hunk 5]
```diff
@@ -0,0 +1,78 @@
...
+        ReferenceOwner a = ReferenceOwner.temporary("a");
+        assertThrows(IllegalStateException.class, () -> referenceCounted.release(a));
+    }
+
+    /**
+     * This is actually a deviation from the contract, it should return false rather than throwing
+     * <p>
+     * Should we fix the contract or fix the behaviour?
+     */
+    @Test
```
Comment (nicktindall) [inline src/test/java/net/openhft/chronicle/core/io/TracingReferenceCountedTest.java:45]: Tracing and Vanilla both throw `IllegalStateExceptions` when `reservedBy` is called with an owner that doesn't have a reservation. The interface says they should return false, we should change the implementations or the interface javadoc to be consistent. I've changed neither so far.

File: src/main/java/net/openhft/chronicle/core/io/ReferenceCountedTracer.java (hunk 2 above)
Comment (peter-lawrey) [reply src/main/java/net/openhft/chronicle/core/io/ReferenceCountedTracer.java:31]: As long as we are confident the tests are comprehensive enough, this is fine. 
What is the benefit of this change?

File: src/main/java/net/openhft/chronicle/core/io/TracingReferenceCounted.java (hunk 3 above)
Comment (peter-lawrey) [reply src/main/java/net/openhft/chronicle/core/io/TracingReferenceCounted.java:150]: When you check which reference still holds on to the resource,  you would have two stack traces of owners not released when one of them was actually attempted. i.e. isn't the source of an issue. This is likely to be more confusing than useful.

File: src/main/java/net/openhft/chronicle/core/io/TracingReferenceCounted.java (hunk 4 above)
Comment (peter-lawrey) [reply src/main/java/net/openhft/chronicle/core/io/TracingReferenceCounted.java:243]: +1 The method name does imply that they should be released.

File: src/main/java/net/openhft/chronicle/core/io/VanillaReferenceCounted.java [hunk 6]
```diff
@@ -158,10 +157,17 @@ public void throwExceptionIfNotReleased() throws IllegalStateException {
...
+            final int refCount = refCount();
+            if (refCount == 0) {
+                break;
+            }
+            if (valueCompareAndSet(refCount, 0)) {
+                if (!unmonitored && !AbstractCloseable.DISABLE_DISCARD_WARNING)
+                    Jvm.warn().on(type, "Discarded without being released");
+                callOnRelease();
+                break;
+            }
```
Comment (peter-lawrey) [inline src/main/java/net/openhft/chronicle/core/io/VanillaReferenceCounted.java]: This extra code reduces the chance of showing a warning when you want it to detect incorrect behaviour as early as possible.

Comment (peter-lawrey) [reply src/main/java/net/openhft/chronicle/core/io/VanillaReferenceCounted.java]: If anything, you want to more reliably show a warning than avoid it.

File: src/test/java/net/openhft/chronicle/core/io/TracingReferenceCountedTest.java (hunk 5 above)
Comment (peter-lawrey) [reply src/test/java/net/openhft/chronicle/core/io/TracingReferenceCountedTest.java:45]: The interface should show the contract that all implementations follow. The Vanilla can't detect duplicate reserves so it can't throw an ISE. The contract could say it may or may not throw an ISE depending on settings.

**Review by peter-lawrey — CHANGES_REQUESTED** [review]
Significant improvements, and highlighted the need to document some unclear behaviour.

File: src/main/java/net/openhft/chronicle/core/io/ReferenceCountedTracer.java (hunk 2 above)
Comment (nicktindall) [reply src/main/java/net/openhft/chronicle/core/io/ReferenceCountedTracer.java:31]: See https://github.com/OpenHFT/Chronicle-Core/issues/445 (linked in the description & commit). DualReferenceCounted means event handlers e.g. the current `onRelease` handler and the proposed `ReferenceChangeListener` will be executed inside a synchronized block. We shouldn't execute arbitrary code while holding a resource as it introduces the risk of a deadlock. The first use of `ReferenceChangeListener`, triggering a cache flush in `ReferenceCountedCache`, did deadlock when executed synchronously.

File: src/main/java/net/openhft/chronicle/core/io/TracingReferenceCounted.java (hunk 3 above)
Comment (nicktindall) [reply src/main/java/net/openhft/chronicle/core/io/TracingReferenceCounted.java:150]: Good point, I'll change Vanilla & the contract test to match this behaviour instead

File: src/test/java/net/openhft/chronicle/core/io/TracingReferenceCountedTest.java (hunk 5 above)
Comment (nicktindall) [reply src/test/java/net/openhft/chronicle/core/io/TracingReferenceCountedTest.java:45]: The interface states that the two possible return values are `true`/`false` (as you'd expect given it returns a boolean). There is no mention of any exceptional cases. It accounts for the fact that some implementations may not know by stating

> Returns <code>true</code> if not sure.

(see below)
```
    /**
     * Best effort check the owner has reserved it. Returns <code>true</code> if not sure.
     *
     * @param owner to check
     * @return false if the owner definitely doesn't own it.
     */
```

I think we should never throw an exception, otherwise if someone wants to know if something is reserved by or not they need to implement
```
boolean actuallyReservedBy() {
    try {
        return bytes.reservedBy(owner);
    } catch (IllegalStateException e) {
        // assume that exception means definitely not, as it seems to
        return false;
    }
}
```
Which seems pretty clunky. If you look at the current implementations, the return value is redundant. None of them will ever return false.

I checked where it's used (see [here](https://github.com/search?p=2&q=org%3AOpenHFT+reservedBy&type=Code), [here](https://github.com/search?q=org%3AChronicleEnterprise+reservedBy&type=Code) and [here](https://github.com/search?q=org%3AChronicleSoftware+reservedBy&type=Code)) and it's only used in assertions, if we return false instead of throwing an exception, we just get an `AssertionError` instead of and `IllegalStateException` when assertions are turned on.

What do you think?

File: src/main/java/net/openhft/chronicle/core/io/VanillaReferenceCounted.java (hunk 6 above)
Comment (nicktindall) [reply src/main/java/net/openhft/chronicle/core/io/VanillaReferenceCounted.java]: Good point, I'll change that.

File: src/main/java/net/openhft/chronicle/core/io/VanillaReferenceCounted.java [hunk 7]
```diff
@@ -124,20 +123,21 @@ public void callOnRelease() throws ClosedIllegalStateException {
...
+        }
+        if (value > 0) {
+            final IllegalStateException ise = new IllegalStateException(type.getName() + " not the last released");
+            if (thrownException != null) {
+                ise.addSuppressed(thrownException);
             }
+            throw ise;
+        }
+        if (thrownException != null) {
+            Jvm.rethrow(thrownException);
```
Comment (nicktindall) [inline src/main/java/net/openhft/chronicle/core/io/VanillaReferenceCounted.java:145]: As discussed this behaviour was changed to match that of `TracingReferenceCounted`, i.e. when the reference released is not the last, it will be released then an exception will be thrown.

File: src/main/java/net/openhft/chronicle/core/io/VanillaReferenceCounted.java [hunk 8]
```diff
@@ -97,6 +96,10 @@ private boolean valueCompareAndSet(int from, int to) {
         return UnsafeMemory.INSTANCE.compareAndSwapInt(this, VALUE, from, to);
     }
 
+    private int valueGetAndSet(int to) {
+        return UnsafeMemory.INSTANCE.getAndSetInt(this, VALUE, to);
```
Comment (nicktindall) [inline src/main/java/net/openhft/chronicle/core/io/VanillaReferenceCounted.java:101]: I had to add this atomically get and set the value.

File: src/main/java/net/openhft/chronicle/core/io/VanillaReferenceCounted.java [hunk 9]
```diff
@@ -158,9 +162,9 @@ public void throwExceptionIfNotReleased() throws IllegalStateException {
 
     @Override
     public void warnAndReleaseIfNotReleased() throws ClosedIllegalStateException {
-        if (refCount() > 0) {
+        if (valueGetAndSet(0) > 0) {
             if (!unmonitored && !AbstractCloseable.DISABLE_DISCARD_WARNING)
-                Slf4jExceptionHandler.WARN.on(type, "Discarded without being released");
+                Jvm.warn().on(type, "Discarded without being released");
             callOnRelease();
```
Comment (nicktindall) [inline src/main/java/net/openhft/chronicle/core/io/VanillaReferenceCounted.java:169]: We do atomic get-and-set to ensure we were the ones to take the value to zero and it's safe to `callOnRelease`

File: src/test/java/net/openhft/chronicle/core/io/TracingReferenceCountedTest.java (hunk 5 above)
Comment (nicktindall) [reply src/test/java/net/openhft/chronicle/core/io/TracingReferenceCountedTest.java:45]: Another option might be to deprecate the current method and change it to `assertReservedBy(owner)`, which could throw an exception for the definitely not case and not return anything. (i.e. current behaviour without the redundant return value)

File: src/main/java/net/openhft/chronicle/core/Memory.java [hunk 10]
```diff
@@ -164,6 +164,10 @@ default long heapUsed() {
 
     boolean compareAndSwapLong(Object object, long offset, long expected, long value) throws MisAlignedAssertionError;
 
+    int getAndSetInt(long address, int value) throws MisAlignedAssertionError;
+
+    int getAndSetInt(Object object, long offset, int value) throws MisAlignedAssertionError;
```
Comment (nicktindall) [inline src/main/java/net/openhft/chronicle/core/Memory.java:169]: I needed this for `VanillaReferenceCounted#warnAndReleaseIfNotReleased`. Not sure if we want to call this `getAndSet` (consistent with `Unsafe`) or `readAndWrite` (consistent with `Memory`). `compareAndSwap` is consistent with `Unsafe`, so I went with `getAndSet`

File: src/test/java/net/openhft/chronicle/core/io/ReferenceCountedContractTest.java [hunk 11]
```diff
@@ -0,0 +1,242 @@
...
+    public void reservedByWillReturnTrueWhenOwnerHasReferenceReserved() {
+        ReferenceCounted referenceCounted = createReferenceCounted();
+
+        ReferenceOwner a = ReferenceOwner.temporary("a");
+        referenceCounted.reserve(a);
+        assertTrue(referenceCounted.reservedBy(a));
+    }
+
+    @Test
+    public void implementationsShouldBeThreadSafe() throws InterruptedException {
```
Comment (nicktindall) [inline src/test/java/net/openhft/chronicle/core/io/ReferenceCountedContractTest.java:164]: Added this to weed out any thread-safety issues in ReferenceCounted implementations

File: src/test/java/net/openhft/chronicle/core/io/TracingReferenceCountedTest.java (hunk 5 above)
Comment (nicktindall) [reply src/test/java/net/openhft/chronicle/core/io/TracingReferenceCountedTest.java:45]: I did the change to make them consistent with the current interface (i.e. not throwing exceptions). The tracing reference counted will still log a warning when false to distinguish between never-held and held-then-released.

It went through build-all OK, but happy to do something else if you think there's a better solution.

File: src/main/java/net/openhft/chronicle/core/io/AbstractCloseable.java (hunk 1 above)
Comment (peter-lawrey) [reply src/main/java/net/openhft/chronicle/core/io/AbstractCloseable.java:48]: The purpose was that Jvm.warn() are checked in tests and but Slf4j..WARN isn't; 
We have another means of ignoring warnings, which could be ignored in the XxxxTestCommon instead.

File: src/main/java/net/openhft/chronicle/core/io/TracingReferenceCounted.java (hunk 3 above)
Comment (peter-lawrey) [reply src/main/java/net/openhft/chronicle/core/io/TracingReferenceCounted.java:150]: We don't have a test to show the expected message when the resources check fails.

File: src/test/java/net/openhft/chronicle/core/io/TracingReferenceCountedTest.java (hunk 5 above)
Comment (peter-lawrey) [reply src/test/java/net/openhft/chronicle/core/io/TracingReferenceCountedTest.java:45]: It's worth considering that the common case is that this level of tracing is off, and this is only useful when tracing is turned on. It's possible this method is no longer useful.

File: src/main/java/net/openhft/chronicle/core/io/VanillaReferenceCounted.java (hunk 8 above)
Comment (peter-lawrey) [reply src/main/java/net/openhft/chronicle/core/io/VanillaReferenceCounted.java:101]: What does this tell you that CAS doesn't?

Comment (nicktindall) [reply src/main/java/net/openhft/chronicle/core/io/VanillaReferenceCounted.java:101]: It allows us to atomically set the value and get the value that was before we set it, that way we can know if we were the ones responsible for changing the value from >=  1 to zero and therefore whether it's safe to call `onRelease`. We _could_ implement `getAndSet` with `compareAndSet` in a loop, but `getAndSet` means we don't have to do that.

File: src/main/java/net/openhft/chronicle/core/io/TracingReferenceCounted.java (hunk 3 above)
Comment (nicktindall) [reply src/main/java/net/openhft/chronicle/core/io/TracingReferenceCounted.java:150]: Sorry do you mean to add a test for the specific messages in the exceptions thrown by `release`? I think if we care that much about specific exceptions being thrown we should make specific exception sub-classes rather than testing message text.

There are tests for the specific messages that are logged when `reservedBy` returns false see [here](https://github.com/OpenHFT/Chronicle-Core/pull/446/files#diff-0149803deb8141c24d380ac84a76e201ca92dfd436d69f44d028ca1012302002R48) and [here](https://github.com/OpenHFT/Chronicle-Core/pull/446/files#diff-0149803deb8141c24d380ac84a76e201ca92dfd436d69f44d028ca1012302002R57)

**Review by JerryShea — APPROVED** [review]

File: src/main/java/net/openhft/chronicle/core/io/TracingReferenceCounted.java (hunk 3 above)
Comment (nicktindall) [reply src/main/java/net/openhft/chronicle/core/io/TracingReferenceCounted.java:150]: I added [some more tests around the specific errors thrown when releaseLast fails](https://github.com/OpenHFT/Chronicle-Core/pull/446/commits/da82b5b5f9312cb053ad993e951c2c807ca557c3)

File: src/test/java/net/openhft/chronicle/core/io/TracingReferenceCountedTest.java (hunk 5 above)
Comment (nicktindall) [reply src/test/java/net/openhft/chronicle/core/io/TracingReferenceCountedTest.java:45]: I think if we just make the implementation match the interface as I've done, I'm happy to leave it there or it's becoming scope creep. There's also [a bunch of logic in TracingReferenceCounted](https://github.com/OpenHFT/Chronicle-Core/blob/b546716e3ef70139567886a3d6873c3167d7edff/src/main/java/net/openhft/chronicle/core/io/TracingReferenceCounted.java#L180) that looks like it could do with a tidy up and some more testing, but again it's scope creep for this PR. I'm happy where it's at for now and if we want to do more I suggest we create issues and more PRs later.

File: src/main/java/net/openhft/chronicle/core/io/TracingReferenceCounted.java (hunk 3 above)
Comment (peter-lawrey) [reply src/main/java/net/openhft/chronicle/core/io/TracingReferenceCounted.java:150]: I can't see the commits, but I believe you

File: src/test/java/net/openhft/chronicle/core/io/TracingReferenceCountedTest.java (hunk 5 above)
Comment (peter-lawrey) [reply src/test/java/net/openhft/chronicle/core/io/TracingReferenceCountedTest.java:45]: Can you mark it as deprecated for removal in x.25, and leave it for now ?

File: src/main/java/net/openhft/chronicle/core/io/VanillaReferenceCounted.java (hunk 8 above)
Comment (peter-lawrey) [reply src/main/java/net/openhft/chronicle/core/io/VanillaReferenceCounted.java:101]: We can't force the release of the resource. If releaseLast is called while another thread still uses the resource, we can't have it SEG faulting.

**Review by peter-lawrey — APPROVED** [review]
These changes look like a good improvement
