### PR TITLE
Return Closeable to allow cancellation of scheduled tasks in Timer…

### LINKED ISSUE #462: Add a way to cancel scheduled handlers submitted to a Timer
Currently there's no way to cancel a task submitted via `Timer#schedule*` methods. ScheduledEventHandler implements closeable and is coded to throw InvalidHandlerException after it's closed but there's no way to get a reference to the handler to do that.

### PR DESCRIPTION
**Pull request by nicktindall**
…add tests for Timer, make Timer's TimeProvider configurable. Fixes #462.

### CODE REVIEW

File: src/test/java/net/openhft/chronicle/core/threads/TimerTest.java [hunk 1]
```diff
@@ -0,0 +1,131 @@
...
+import static org.mockito.ArgumentMatchers.any;
+import static org.mockito.Mockito.*;
+
+@ExtendWith(MockitoExtension.class)
+class TimerTest {
+
+    public static final int INITIAL_DELAY_MS = 1_000;
+    public static final int PERIOD_MS = 2_000;
+    @Mock
+    private EventLoop eventLoop;
```
Comment (nicktindall) [inline src/test/java/net/openhft/chronicle/core/threads/TimerTest.java:24]: There are no EventLoop implementations in Core so we have no choice but to mock here, also the tests read nicely and involve no threads with the mocked EventLoop.

**Review by JerryShea — APPROVED** [review]
